version: 2

builds:
  - main: ./cmd/pollex
    binary: pollex
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    files:
      - prompts/polish.txt
      - deploy/config.yaml.example

changelog:
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^ci:"
